### ISSUE TITLE
how is it used?

### ISSUE THREAD

**Issue by ghost** [adituv/gsmagic#2]
I was looking for an editor for golden sun and I came across this, but since I don't know anything about programming I don't know how to use it xd
Do I have to download any program? I want to learn how to use it but I'm new :(

**Comment by adituv** [comment]
The version here is out of date.  This is a mirror of Teawater’s source code from a 2018 build, from back when I was planning to extend the editor.  Unfortunately that never happened.

I’d personally ask around on the Golden Sun Hacking Community forums or discord server; this thread looks promising - <http://forum.goldensunhacking.net/index.php?topic=3143.0 <http://forum.goldensunhacking.net/index.php?topic=3143.0>

**Comment by ghost** [comment]
Thank youuuu <3
I was looking everywhere but I didnt find anything,
